Adding comments to functions
shiftie/gulp-marketing pull request #1
Opened 2017-05-15 17:57 UTC by haabaato

- small tweak to require only the `gulp/tasks` folder since the task configs are loaded by each task anyway
- added comments to most functions.  Please confirm that I'm correctly understanding the behavior of each function

2017-05-16 07:32 UTC, shiftie requested changes

2017-05-16 07:32 UTC, shiftie commented on gulp/tasks/set-env.js
> + */
not only scss, we ill have to provide values to JS (via a module that exports that variable) & to PHP (via $GLOBALS array i guess)

2017-05-16 07:32 UTC, shiftie commented on gulp/tasks/styles.js
> + * Sets up the watcher for changes in css files, and compiles changed files.
watch only in debug (dev mode) & watches scss files (not css)

2017-05-16 20:41 UTC, haabaato commented
ok updated the comments

2017-05-17 07:34 UTC, shiftie approved these changes

2017-05-17 07:36 UTC, merged